# Generated by Django 5.0.6 on 2024-05-28 08:15

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_host_alter_eventmemories_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.upload_to),
        ),
    ]
