# Generated by Django 5.0.6 on 2024-05-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_post', to='event.eventpost'),
            preserve_default=False,
        ),
    ]
