# Generated by Django 5.0.6 on 2024-05-29 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_eventpost_event_event_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_post', to='event.eventpost'),
        ),
    ]
