# Generated by Django 5.0.6 on 2024-05-29 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_post_eventpost_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_posts', to='event.eventpost'),
        ),
    ]
