# Generated by Django 5.0.6 on 2024-05-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_eventpost_event_event_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='posts',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventmemories',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories_event', to='event.event'),
        ),
    ]
