# Generated by Django 5.0.6 on 2024-05-30 06:16

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_event_posts_eventpost_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.upload_to),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
