# Generated by Django 5.0.6 on 2024-05-31 01:18

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_eventpost_image_alter_eventpost_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmemories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.upload_to),
        ),
    ]
