# Generated by Django 5.0.6 on 2024-05-31 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_eventmemories_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmemories',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='event.event'),
        ),
    ]
