# Generated by Django 5.0.6 on 2024-05-31 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_eventmemories_event'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmemories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to='user.profile'),
        ),
    ]
