# Generated by Django 5.0.6 on 2024-05-31 09:55

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_eventmemories_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.upload_to),
        ),
    ]
