# Generated by Django 5.0.6 on 2024-06-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_event_host_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
