# Generated by Django 5.0.6 on 2024-09-14 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_alter_eventpost_message'),
        ('user', '0006_alter_profile_user_memories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMemories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_events', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMemoriesComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_event_comments', to='event.profilememories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_of_comment', to='user.profile')),
            ],
        ),
    ]
