# Generated by Django 5.0.6 on 2024-09-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_profilememories_profilememoriescomments'),
        ('user', '0014_remove_profile_user_memories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilememories',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_memories', to='user.profile'),
        ),
    ]
