# Generated by Django 5.0.6 on 2024-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_eventuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='extra_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
