# Generated by Django 5.0.6 on 2024-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_eventuser_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='extra_info',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
