# Generated by Django 5.0.6 on 2024-09-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profile_user_memories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_memories',
        ),
    ]
