# Generated by Django 5.0.6 on 2024-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_profilememories_profilememoriescomments'),
        ('user', '0012_remove_profile_user_memories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_memories',
            field=models.ManyToManyField(blank=True, to='event.profilememories'),
        ),
    ]
